# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from main.proto import service_pb2 as main_dot_proto_dot_service__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Greeter/SayHello',
        request_serializer=main_dot_proto_dot_service__pb2.HelloRequest.SerializeToString,
        response_deserializer=main_dot_proto_dot_service__pb2.HelloReply.FromString,
        )
    self.GetData = channel.unary_unary(
        '/Greeter/GetData',
        request_serializer=main_dot_proto_dot_service__pb2.DataMessage.SerializeToString,
        response_deserializer=main_dot_proto_dot_service__pb2.DataMessage.FromString,
        )
    self.DataChannel = channel.stream_stream(
        '/Greeter/DataChannel',
        request_serializer=main_dot_proto_dot_service__pb2.DataMessage.SerializeToString,
        response_deserializer=main_dot_proto_dot_service__pb2.DataMessage.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataChannel(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=main_dot_proto_dot_service__pb2.HelloRequest.FromString,
          response_serializer=main_dot_proto_dot_service__pb2.HelloReply.SerializeToString,
      ),
      'GetData': grpc.unary_unary_rpc_method_handler(
          servicer.GetData,
          request_deserializer=main_dot_proto_dot_service__pb2.DataMessage.FromString,
          response_serializer=main_dot_proto_dot_service__pb2.DataMessage.SerializeToString,
      ),
      'DataChannel': grpc.stream_stream_rpc_method_handler(
          servicer.DataChannel,
          request_deserializer=main_dot_proto_dot_service__pb2.DataMessage.FromString,
          response_serializer=main_dot_proto_dot_service__pb2.DataMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
